### ISSUE TITLE
caffe fails to import with gflags 2.2.0 package

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/caffe-feedstock#29]
The gflags 2.2.0 package does not provide a `libgflags.so.2` file (conda-forge/gflags-feedstock#9) which causes an issue with the current `caffe` build on Linux as the package links against this library.  

Update the requirements to `gflags >=2.2` and rebuilding the package will fix the immediate issue although the existing packages will still be broken as their requirements should be `gflags <2.2`.

```
(caffe_test) ~$ python -c "import caffe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/anaconda3/envs/caffe_test/lib/python3.6/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/jhelmus/anaconda3/envs/caffe_test/lib/python3.6/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libgflags.so.2: cannot open shared object file: No such file or directory
```

**Comment by jakirkham** [comment]
Would it make sense to just make this require `gflags 2.2.*` so as to avoid the same issue with `2.3.*`?

**Comment by jjhelmus** [comment]
> Would it make sense to just make this require gflags 2.2.* so as to avoid the same issue with 2.3.*?

Yes, the linkage in a newly build file will be to `libgflags.so.2.2` so this explicit pinning would make sense.

**Comment by supun-kanda** [comment]
In my case intalling protobuf solved the problem
