### ISSUE TITLE
binary is linked to opencv 3.3

### ISSUE THREAD

**Issue by escorciav** [conda-forge/caffe-feedstock#40]
Hi,
I noticed that `libcaffe.so` is linked to opencv 3.3. However the requirement in the `.yaml` is broad `3.*`. Thus, a fresh install gave me opencv 3.4.
I fixed it by downgrading opencv manually.
Thanks for providing this!
Victor

**Comment by marcelotrevisani** [comment]
We upgraded it to opencv 4 for now. I think that is solved then right!?

**Comment by escorciav** [comment]
Thanks for fixing it.

I swamped with a few tasks. It may take me a while to verify it as I lost the project where I used this. Sorry.

BTW, I started using the anaconda binaries as they were shipped with GPU support.

- Are you doing the same? if not, any suggestion to enable GPU support?
