### ISSUE TITLE
Latest build not linked properly to leveldb

### ISSUE THREAD

**Issue by lukeyeager** [conda-forge/caffe-feedstock#42]
```
/opt/conda/lib/python3.6/site-packages/caffe/../../../libcaffe.so.1.0.0:
    undefined symbol: _ZNK7leveldb6Status8ToStringB5cxx11Ev
```

**Comment by lukeyeager** [comment]
Installed with this command. I think this comes back to this GitHub repo eventually?
```
conda install -y -c anaconda caffe
```

**Comment by lukeyeager** [comment]
This fixes the problem for me:
```
conda install -y glog leveldb
```
When I update those packages to the latest versions, then I can import caffe without issues.
Seems like a dependency version problem of some sort.

**Comment by jjhelmus** [comment]
Also note that mixing packages between the `conda-forge` and `defaults` channels can cause compatibility issues like this, it is best to use one channel or the other.  This is especially true for packages with a number of C++ dependencies like caffe.

**Comment by lukeyeager** [comment]
Thanks for the clarification, @jakirkham. Will post over there...

**Comment by Francoforever** [comment]
This works for me. Thx!
